name: docker-php
services:
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - "9000:9000" # expose --> ports
    volumes:
      - /var/www/html/verdor
      - ./app:/var/www/html
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: docker_php
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306" # port mapping for external access
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped

  web:
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    restart: unless-stopped

volumes:
  mysqldata:
